<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vML"
    nsURI="http://www.visualligence.com/g/VML" nsPrefix="vML">
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputtype" eType="#//TypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputtype" eType="#//TypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentences" upperBound="-1"
        eType="#//Sentence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sentence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Sentence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" eType="#//LiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="#//LiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//RStreamValue"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Op">
    <eLiterals name="and" literal="&amp;&amp;"/>
    <eLiterals name="or" value="1" literal="||"/>
    <eLiterals name="neg" literal="!"/>
    <eLiterals name="eq" literal="=="/>
    <eLiterals name="ne" value="1" literal="!="/>
    <eLiterals name="lt" value="2" literal="&lt;"/>
    <eLiterals name="gt" value="3" literal=">"/>
    <eLiterals name="le" value="4" literal="&lt;="/>
    <eLiterals name="ge" value="5" literal=">="/>
    <eLiterals name="plus" literal="+"/>
    <eLiterals name="minus" value="1" literal="-"/>
    <eLiterals name="times" literal="*"/>
    <eLiterals name="modulo" value="1" literal="%"/>
    <eLiterals name="intdivision" value="2" literal="//"/>
    <eLiterals name="divideby" value="3" literal="/"/>
    <eLiterals name="exp" literal="**"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RValue" eSuperTypes="#//LiteralExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//LoopSentence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantRef" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantref" eType="#//Constant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleLiteral" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceLiteral" eSuperTypes="#//RValue #//LoopFor"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceLiteralSerie" eSuperTypes="#//SequenceLiteral">
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//LiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//LiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inc" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceLiteralPlain" eSuperTypes="#//SequenceLiteral">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//LiteralExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleLiteral" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//TupleItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentences" upperBound="-1"
        eType="#//Sentence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Noop" eSuperTypes="#//Sentence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multi" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Op"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Multi"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//Sentence"/>
  <eClassifiers xsi:type="ecore:EClass" name="DUnit" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Op"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multi" eType="#//Multi"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NUnit" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numbertype" eType="#//NumberType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Box" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//Sentence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Member">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlainTypeRef" eSuperTypes="#//TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeTypeRef" eSuperTypes="#//TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceTypeRef" eSuperTypes="#//CompositeTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleTypeRef" eSuperTypes="#//CompositeTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//TupleTypeRefItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleTypeRefItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetTypeRef" eSuperTypes="#//CompositeTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidTypeRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoTypeRef" eSuperTypes="#//PlainTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="#//CollectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeref" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unittype" eType="#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoxRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Box"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeAliasRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//TypeAlias"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuxTypeRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="#//AuxType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShapeRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Shape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberTypeRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="#//NumberType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualTypeRef" eSuperTypes="#//PlainTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="#//VisualType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumberType">
    <eLiterals name="positive" literal="positive"/>
    <eLiterals name="natural" value="1" literal="natural"/>
    <eLiterals name="integer" value="2" literal="integer"/>
    <eLiterals name="rational" value="3" literal="rational"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisualType">
    <eLiterals name="shape" literal="shape"/>
    <eLiterals name="color" value="1" literal="color"/>
    <eLiterals name="angle" value="2" literal="angle"/>
    <eLiterals name="size" value="3" literal="size"/>
    <eLiterals name="position" value="4" literal="position"/>
    <eLiterals name="texture" value="5" literal="texture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuxType">
    <eLiterals name="string" literal="string"/>
    <eLiterals name="bool" value="1" literal="bool"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeAlias" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionType">
    <eLiterals name="set" literal="set"/>
    <eLiterals name="bag" value="1" literal="bag"/>
    <eLiterals name="list" value="2" literal="list"/>
    <eLiterals name="graph" value="3" literal="graph"/>
    <eLiterals name="single" value="4" literal="single"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stream" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//LStreamValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//RStreamValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LStreamValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="RStreamValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputRef" eSuperTypes="#//RStreamValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputRef" eSuperTypes="#//LStreamValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invokation" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentences" upperBound="-1"
        eType="#//InvokationParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokationParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="it" eType="#//LoopFor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentences" upperBound="-1"
        eType="#//LoopSentence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopSentence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="o" eType="#//LiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="i" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopFor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Factory" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isinput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Canvas" eSuperTypes="#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Pair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//LiteralExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Op"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperation" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Op"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//LiteralExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
