/*
* generated by Xtext
*/
package com.visualligence.g;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.visualligence.g.ui.internal.VMLActivator.getInstance().getInjector("com.visualligence.g.VML");
	}
	
}
