/*
* generated by Xtext
*/
package com.visualligence.g.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.visualligence.g.services.VMLGrammarAccess;

public class VMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private VMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.visualligence.g.parser.antlr.internal.InternalVMLParser createParser(XtextTokenStream stream) {
		return new com.visualligence.g.parser.antlr.internal.InternalVMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public VMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
