/*
 * generated by Xtext
 */
package com.visualligence.g;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VMLRuntimeModule extends com.visualligence.g.AbstractVMLRuntimeModule {

}
