/*
* generated by Xtext
*/
package com.visualligence.g.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.visualligence.g.services.VMLGrammarAccess;

public class VMLParser extends AbstractContentAssistParser {
	
	@Inject
	private VMLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.visualligence.g.ui.contentassist.antlr.internal.InternalVMLParser createParser() {
		com.visualligence.g.ui.contentassist.antlr.internal.InternalVMLParser result = new com.visualligence.g.ui.contentassist.antlr.internal.InternalVMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeDeclAccess().getAlternatives(), "rule__TypeDecl__Alternatives");
					put(grammarAccess.getStreamAccess().getAlternatives(), "rule__Stream__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getModuleAccess().getGroup(), "rule__Module__Group__0");
					put(grammarAccess.getModuleAccess().getGroup_4(), "rule__Module__Group_4__0");
					put(grammarAccess.getModuleAccess().getGroup_4_3(), "rule__Module__Group_4_3__0");
					put(grammarAccess.getModuleAccess().getGroup_5(), "rule__Module__Group_5__0");
					put(grammarAccess.getModuleAccess().getGroup_5_3(), "rule__Module__Group_5_3__0");
					put(grammarAccess.getModuleAccess().getGroup_6(), "rule__Module__Group_6__0");
					put(grammarAccess.getModuleAccess().getGroup_6_3(), "rule__Module__Group_6_3__0");
					put(grammarAccess.getModuleAccess().getGroup_7(), "rule__Module__Group_7__0");
					put(grammarAccess.getModuleAccess().getGroup_7_3(), "rule__Module__Group_7_3__0");
					put(grammarAccess.getInputAccess().getGroup(), "rule__Input__Group__0");
					put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
					put(grammarAccess.getOutputAccess().getGroup_5(), "rule__Output__Group_5__0");
					put(grammarAccess.getModuleInstancesAccess().getGroup(), "rule__ModuleInstances__Group__0");
					put(grammarAccess.getModuleInstancesAccess().getGroup_5(), "rule__ModuleInstances__Group_5__0");
					put(grammarAccess.getModuleInstancesAccess().getGroup_5_3(), "rule__ModuleInstances__Group_5_3__0");
					put(grammarAccess.getStream_ImplAccess().getGroup(), "rule__Stream_Impl__Group__0");
					put(grammarAccess.getLiteralAccess().getGroup(), "rule__Literal__Group__0");
					put(grammarAccess.getLiteralAccess().getGroup_3(), "rule__Literal__Group_3__0");
					put(grammarAccess.getNativeTypeAccess().getGroup(), "rule__NativeType__Group__0");
					put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
					put(grammarAccess.getHashAccess().getGroup(), "rule__Hash__Group__0");
					put(grammarAccess.getHashAccess().getGroup_4(), "rule__Hash__Group_4__0");
					put(grammarAccess.getHashAccess().getGroup_4_3(), "rule__Hash__Group_4_3__0");
					put(grammarAccess.getHashItemAccess().getGroup(), "rule__HashItem__Group__0");
					put(grammarAccess.getModuleAccess().getNameAssignment_2(), "rule__Module__NameAssignment_2");
					put(grammarAccess.getModuleAccess().getInputAssignment_4_2(), "rule__Module__InputAssignment_4_2");
					put(grammarAccess.getModuleAccess().getInputAssignment_4_3_1(), "rule__Module__InputAssignment_4_3_1");
					put(grammarAccess.getModuleAccess().getOutputAssignment_5_2(), "rule__Module__OutputAssignment_5_2");
					put(grammarAccess.getModuleAccess().getOutputAssignment_5_3_1(), "rule__Module__OutputAssignment_5_3_1");
					put(grammarAccess.getModuleAccess().getInstancesAssignment_6_2(), "rule__Module__InstancesAssignment_6_2");
					put(grammarAccess.getModuleAccess().getInstancesAssignment_6_3_1(), "rule__Module__InstancesAssignment_6_3_1");
					put(grammarAccess.getModuleAccess().getTypesAssignment_7_2(), "rule__Module__TypesAssignment_7_2");
					put(grammarAccess.getModuleAccess().getTypesAssignment_7_3_1(), "rule__Module__TypesAssignment_7_3_1");
					put(grammarAccess.getInputAccess().getNameAssignment_1(), "rule__Input__NameAssignment_1");
					put(grammarAccess.getInputAccess().getTypeAssignment_4(), "rule__Input__TypeAssignment_4");
					put(grammarAccess.getOutputAccess().getNameAssignment_1(), "rule__Output__NameAssignment_1");
					put(grammarAccess.getOutputAccess().getTypeAssignment_4(), "rule__Output__TypeAssignment_4");
					put(grammarAccess.getOutputAccess().getLeftAssignment_5_1(), "rule__Output__LeftAssignment_5_1");
					put(grammarAccess.getModuleInstancesAccess().getNameAssignment_1(), "rule__ModuleInstances__NameAssignment_1");
					put(grammarAccess.getModuleInstancesAccess().getDescAssignment_4(), "rule__ModuleInstances__DescAssignment_4");
					put(grammarAccess.getModuleInstancesAccess().getLeftAssignment_5_2(), "rule__ModuleInstances__LeftAssignment_5_2");
					put(grammarAccess.getModuleInstancesAccess().getLeftAssignment_5_3_1(), "rule__ModuleInstances__LeftAssignment_5_3_1");
					put(grammarAccess.getStream_ImplAccess().getNameAssignment_1(), "rule__Stream_Impl__NameAssignment_1");
					put(grammarAccess.getStream_ImplAccess().getTypeAssignment_4(), "rule__Stream_Impl__TypeAssignment_4");
					put(grammarAccess.getLiteralAccess().getNameAssignment_1(), "rule__Literal__NameAssignment_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_3_1(), "rule__Literal__ValueAssignment_3_1");
					put(grammarAccess.getLiteralAccess().getTypeAssignment_5(), "rule__Literal__TypeAssignment_5");
					put(grammarAccess.getNativeTypeAccess().getNameAssignment_1(), "rule__NativeType__NameAssignment_1");
					put(grammarAccess.getNativeTypeAccess().getTypeAssignment_4(), "rule__NativeType__TypeAssignment_4");
					put(grammarAccess.getListAccess().getNameAssignment_1(), "rule__List__NameAssignment_1");
					put(grammarAccess.getListAccess().getTypeAssignment_4(), "rule__List__TypeAssignment_4");
					put(grammarAccess.getHashAccess().getNameAssignment_2(), "rule__Hash__NameAssignment_2");
					put(grammarAccess.getHashAccess().getItemsAssignment_4_2(), "rule__Hash__ItemsAssignment_4_2");
					put(grammarAccess.getHashAccess().getItemsAssignment_4_3_1(), "rule__Hash__ItemsAssignment_4_3_1");
					put(grammarAccess.getHashItemAccess().getNameAssignment_1(), "rule__HashItem__NameAssignment_1");
					put(grammarAccess.getHashItemAccess().getTypeAssignment_4(), "rule__HashItem__TypeAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.visualligence.g.ui.contentassist.antlr.internal.InternalVMLParser typedParser = (com.visualligence.g.ui.contentassist.antlr.internal.InternalVMLParser) parser;
			typedParser.entryRuleModule();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public VMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
