/*
* generated by Xtext
*/
package com.visualligence.g.ui.contentassist;

import com.visualligence.g.ui.contentassist.AbstractVMLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class VMLProposalProvider extends AbstractVMLProposalProvider {

}
