/*
 * generated by Xtext
 */
package com.visualligence.g.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.visualligence.g.ui.internal.VMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.visualligence.g.ui.internal.VMLActivator.getInstance().getInjector("com.visualligence.g.VML");
	}
	
}
