/*
 * generated by Xtext
 */
package com.visualligence.g.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VMLUiModule extends com.visualligence.g.ui.AbstractVMLUiModule {
	public VMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
