/*
* generated by Xtext
*/
package com.visualligence.g.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class VMLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
